integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: openai_compatible_gauntlet
  # git_commit:  # OR use your commit hash
  pip_install: -e ".[gpu-flash2,openai]"
  ssh_clone: false  # Should be true if using a private repo
- integration_type: wandb
  entity: mosaic-ml
  project: dependent_deployment_eval_jeremy

command: |
  pip uninstall mosaicml -y
  pip install git+https://github.com/mosaicml/composer.git@dev
  cd llm-foundry/scripts
  composer eval/eval.py /mnt/config/parameters.yaml

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $RUN_NAME
name: pi-inference-deployment-gauntlet-eval
# cluster: r1z1  # replace with your cluster here!
# gpu_num: 8 #
# gpu_type: a100_80gb #

compute:
  gpus: 8
  cluster: r1z1

image: mosaicml/llm-foundry:2.2.1_cu121_flash2-latest

# The below is injected as a YAML file: /mnt/config/parameters.yaml
parameters:
  seed: 1
  max_seq_len: 30000
  device_eval_batch_size: 1
  models:
  - model_name: mosaicml/pi
    model:
      name: fmapi_chat
      base_url: https://pi-eve6-2mt2bncm-valfull-lb2-32k-mz9p3n.inf.hosted-on.mosaicml.hosting/v2/
    tokenizer:
      name: mosaicml/mpt-7b
      kwargs:
        model_name: mosaicml/mpt-7b

  # loggers:
  #   wandb: {}
  # callbacks:
  #   eval_output_logging: {}

  icl_tasks: "eval/yamls/long_context_tasks.yaml"
  eval_gauntlet: "eval/yamls/eval_gauntlet_long_context.yaml"
 