integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: openai_compatible_gauntlet
  # git_commit:  # OR use your commit hash
  pip_install: -e ".[gpu-flash2,openai]"
  ssh_clone: false  # Should be true if using a private repo

command: |
  pip uninstall mosaicml -y
  pip install git+https://github.com/mosaicml/composer.git@dev
  cd llm-foundry/scripts
  composer eval/eval.py /mnt/config/parameters.yaml

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $RUN_NAME
name: mistral-large-inference-deployment-gauntlet-eval
# cluster: r1z1  # replace with your cluster here!
# gpu_num: 8 #
# gpu_type: a100_80gb #

compute:
  gpus: 1
  cluster: r1z2

image: mosaicml/llm-foundry:2.2.1_cu121_flash2-latest

# The below is injected as a YAML file: /mnt/config/parameters.yaml
parameters:
  seed: 1
  max_seq_len: 28000
  device_eval_batch_size: 1
  models:
  - model_name: mistralai/Mistral-large
    model:
      name: fmapi_chat
      base_url: https://Mistral-large-zqjvu-serverless.eastus2.inference.ai.azure.com/v1
      api_key: 8Q9mXqXsOGbIB7CLqA11EuCzg0p6GNI2
      is_local: False
    tokenizer:
      name: mosaicml/mpt-7b
      kwargs:
        model_name: mosaicml/mpt-7b

  # loggers:
  #   wandb: {}
  # callbacks:
  #   eval_output_logging: {}
  icl_tasks:
  - label: gsm8k
    dataset_uri: eval/local_data/api_compatible_gauntlet/symbolic_problem_solving/gsm8k_prepended_8shot.jsonl
    num_fewshot:
    - 0
    icl_task_type: question_answering
    cot_delimiter: "The answer is "
    continuation_delimiter: "\n\nA:"
    question_prelimiter: ""
    do_normalization: false
    early_stopping_criteria:
    - "\n\n"
    - "Question:"
  - label: triviaqa_sm_sub
    dataset_uri: eval/local_data/api_compatible_gauntlet/world_knowledge/triviaqa_sm_sub.jsonl
    num_fewshot:
    - 3
    icl_task_type: question_answering
    do_normalization: true
  - label: jeopardy
    dataset_uri: eval/local_data/api_compatible_gauntlet/world_knowledge/jeopardy_all.jsonl
    num_fewshot:
    - 3
    icl_task_type: language_modeling
    continuation_delimiter: "

      Answer: "
    has_categories: true
  - label: arc_challenge
    dataset_uri: eval/local_data/api_compatible_gauntlet/world_knowledge/arc_challenge.jsonl
    num_fewshot:
    - 25
    icl_task_type: question_answering
    continuation_delimiter: "\n\nAnswer:"
    example_delimiter: \n\n
    early_stopping_criteria:
    - \n\n
    - "Question:"
    - "Q:"
  - label: mmlu
    dataset_uri: eval/local_data/api_compatible_gauntlet/world_knowledge/mmlu.jsonl
    num_fewshot:
    - 5
    icl_task_type: question_answering
    continuation_delimiter: "\n\nAnswer:"
    has_categories: true
    example_delimiter: \n\n
    early_stopping_criteria:
    - \n\n
    - "Question:"
    - "Q:"
  - label: lambada_openai
    dataset_uri: eval/local_data/api_compatible_gauntlet/language_understanding/lambada_openai.jsonl
    num_fewshot:
    - 0
    icl_task_type: language_modeling
  - label: hellaswag
    dataset_uri: eval/local_data/api_compatible_gauntlet/language_understanding/hellaswag.jsonl
    num_fewshot:
    - 10
    icl_task_type: question_answering
    continuation_delimiter: "\n\nAnswer:"
    example_delimiter: \n\n
    early_stopping_criteria:
    - \n\n
    - "Question:"
    - "Q:"
 