max_seq_len: 32768
global_seed: 17

# Run Name
run_name: sft_32k_01 # If left blank, will be read from env var $COMPOSER_RUN_NAME

# Model
model:
  name: hf_causal_lm
  pretrained_model_name_or_path: /mnt/ceph-dataset/zhangkang/work/long-text/long_text/corpus/ckpt/hf_alibi_32k
  pretrained: true  # false: only use the architecture; true: initialize with pretrained weights
  config_overrides:
    max_seq_len: ${max_seq_len}
    attn_config:
      attn_impl: flash
      # Set this to `true` if using `train_loader.dataset.packing_ratio` below
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name:  /mnt/ceph-dataset/zhangkang/work/long-text/long_text/corpus/ckpt/hf_alibi_32k
  kwargs:
    model_max_length: ${max_seq_len}
    padding_side: right
    trust_remote_code: true

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    ############
    hf_name: /mnt/ceph-dataset/zhangkang/work/long-text/long_text/corpus/sft_datasets/long_mixed_32k/
    preprocessing_fn: finetune_example.preprocessing:normal_qa         # chat  
    split: train 
    ############
    shuffle: true
    max_seq_len: ${max_seq_len}
    decoder_only_format: true
    # # Use `python llmfoundry/data/packing.py --yaml-path /path/to/this/yaml/ ...`
    # # to profile this run's optimal packing_ratio as it depends on GPU count,
    # # batch size, sequence length
    # packing_ratio:
  drop_last: true
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 120ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 3.0e-6  # 6e-6 for pretrain
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 3ep
eval_interval: 1
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 16 

# System
seed: ${global_seed}
device_eval_batch_size: 2
#device_train_microbatch_size: 2
device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: DEFAULT # 下次改成 DEFAULT
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  wandb: {}

# Checkpoint to local filesystem or remote object store
save_interval: 1ep
save_num_checkpoints_to_keep: 5  # Important, this cleans up checkpoints saved to DISK
save_folder: /mnt/ceph-dataset/zhangkang/work/long-text/long_text/corpus/ckpt/{run_name}

# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt